// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'articles_repo.dart';

final class _$ArticlesRepo implements ArticlesRepo {
  const _$ArticlesRepo(this._db);

  final Executor _db;

  @override
  Future<Result<ArticleRow?, SqlxError>> bySlug(String slug, int viewerId) {
    return _db.fetchOptional<ArticleRow>(
      r'''
SELECT a.id, a.slug, a.title, a.description, a.body, a.tag_list,
       a.created_at, a.updated_at,
       EXISTS (
         SELECT 1 FROM favorites fv WHERE fv.user_id = $2 AND fv.article_id = a.id
       ) AS favorited,
       (SELECT count(*) FROM favorites fv WHERE fv.article_id = a.id) AS favorites_count,
       u.id AS author_id, u.username AS author_username,
       u.bio AS author_bio, u.image AS author_image,
       EXISTS (
         SELECT 1 FROM follows f WHERE f.follower_id = $2 AND f.followee_id = u.id
       ) AS author_following
FROM articles a
JOIN users u ON u.id = a.author_id
WHERE a.slug = $1
''',
      [slug, viewerId],
      const $ArticleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<ArticleRow>, SqlxError>> list(String? tag, String? author, String? favoritedBy, int limit, int offset, int viewerId) {
    return _db.fetchAll<ArticleRow>(
      r'''
SELECT a.id, a.slug, a.title, a.description, NULL::text AS body, a.tag_list,
       a.created_at, a.updated_at,
       EXISTS (
         SELECT 1 FROM favorites fv WHERE fv.user_id = $6 AND fv.article_id = a.id
       ) AS favorited,
       (SELECT count(*) FROM favorites fv WHERE fv.article_id = a.id) AS favorites_count,
       u.id AS author_id, u.username AS author_username,
       u.bio AS author_bio, u.image AS author_image,
       EXISTS (
         SELECT 1 FROM follows f WHERE f.follower_id = $6 AND f.followee_id = u.id
       ) AS author_following
FROM articles a
JOIN users u ON u.id = a.author_id
WHERE ($1::text IS NULL OR a.tag_list @> ARRAY[$1::text])
  AND ($2::text IS NULL OR u.username = $2::text)
  AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM favorites fv
        JOIN users fu ON fu.id = fv.user_id
        WHERE fv.article_id = a.id AND fu.username = $3::text
      ))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $4 OFFSET $5
''',
      [tag, author, favoritedBy, limit, offset, viewerId],
      const $ArticleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> count(String? tag, String? author, String? favoritedBy) {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*) AS count
FROM articles a
JOIN users u ON u.id = a.author_id
WHERE ($1::text IS NULL OR a.tag_list @> ARRAY[$1::text])
  AND ($2::text IS NULL OR u.username = $2::text)
  AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM favorites fv
        JOIN users fu ON fu.id = fv.user_id
        WHERE fv.article_id = a.id AND fu.username = $3::text
      ))
''',
      [tag, author, favoritedBy],
    );
  }

  @override
  Future<Result<List<ArticleRow>, SqlxError>> feed(int viewerId, int limit, int offset) {
    return _db.fetchAll<ArticleRow>(
      r'''
SELECT a.id, a.slug, a.title, a.description, NULL::text AS body, a.tag_list,
       a.created_at, a.updated_at,
       EXISTS (
         SELECT 1 FROM favorites fv WHERE fv.user_id = $1 AND fv.article_id = a.id
       ) AS favorited,
       (SELECT count(*) FROM favorites fv WHERE fv.article_id = a.id) AS favorites_count,
       u.id AS author_id, u.username AS author_username,
       u.bio AS author_bio, u.image AS author_image,
       TRUE AS author_following
FROM articles a
JOIN users u ON u.id = a.author_id
JOIN follows f ON f.followee_id = a.author_id AND f.follower_id = $1
ORDER BY a.created_at DESC, a.id DESC
LIMIT $2 OFFSET $3
''',
      [viewerId, limit, offset],
      const $ArticleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> feedCount(int viewerId) {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*) AS count
FROM articles a
JOIN follows f ON f.followee_id = a.author_id AND f.follower_id = $1
''',
      [viewerId],
    );
  }

  @override
  Future<Result<ArticleKey?, SqlxError>> keyBySlug(String slug) {
    return _db.fetchOptional<ArticleKey>(
      r'''
SELECT id, slug, author_id, title, description, body, tag_list
FROM articles
WHERE slug = $1
''',
      [slug],
      const $ArticleKeyRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> insert(String slug, String title, String description, String body, List<String> tagList, int authorId) {
    return _db.fetchScalar<int>(
      r'''
INSERT INTO articles (slug, title, description, body, tag_list, author_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
''',
      [slug, title, description, body, tagList, authorId],
    );
  }

  @override
  Future<Result<Unit, SqlxError>> update(int id, String slug, String title, String description, String body, List<String> tagList) {
    return _db.execute(
      r'''
UPDATE articles
SET slug = $2, title = $3, description = $4, body = $5, tag_list = $6,
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE id = $1
''',
      [id, slug, title, description, body, tagList],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> delete(int id) {
    return _db.execute(
      r'''DELETE FROM articles WHERE id = $1''',
      [id],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> favorite(int userId, int articleId) {
    return _db.execute(
      r'''
INSERT INTO favorites (user_id, article_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
''',
      [userId, articleId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> unfavorite(int userId, int articleId) {
    return _db.execute(
      r'''DELETE FROM favorites WHERE user_id = $1 AND article_id = $2''',
      [userId, articleId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<List<TagRow>, SqlxError>> tags() {
    return _db.fetchAll<TagRow>(
      r'''
SELECT tag, count(*) AS uses
FROM articles, unnest(tag_list) AS tag
GROUP BY tag
ORDER BY count(*) DESC, tag
''',
      [],
      const $TagRowRowDeserializer().deserialize,
    );
  }
}
