// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'comments_repo.dart';

final class _$CommentsRepo implements CommentsRepo {
  const _$CommentsRepo(this._db);

  final Executor _db;

  @override
  Future<Result<List<CommentRow>, SqlxError>> forArticle(int articleId, int viewerId) {
    return _db.fetchAll<CommentRow>(
      r'''
SELECT c.id, c.body, c.created_at, c.updated_at,
       u.id AS author_id, u.username AS author_username,
       u.bio AS author_bio, u.image AS author_image,
       EXISTS (
         SELECT 1 FROM follows f WHERE f.follower_id = $2 AND f.followee_id = u.id
       ) AS author_following
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.article_id = $1
ORDER BY c.id DESC
''',
      [articleId, viewerId],
      const $CommentRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<NewCommentRow, SqlxError>> insert(int articleId, int authorId, String body) {
    return _db.fetchOne<NewCommentRow>(
      r'''
INSERT INTO comments (article_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, body, created_at, updated_at
''',
      [articleId, authorId, body],
      const $NewCommentRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<CommentKey?, SqlxError>> keyById(int id) {
    return _db.fetchOptional<CommentKey>(
      r'''SELECT id, article_id, author_id FROM comments WHERE id = $1''',
      [id],
      const $CommentKeyRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> delete(int id) {
    return _db.execute(
      r'''DELETE FROM comments WHERE id = $1''',
      [id],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
