// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'database.dart';

final class _$ConduitDatabase implements ConduitDatabase {
  _$ConduitDatabase._(this._driver);

  factory _$ConduitDatabase.connect(
    String url, {
    PgConnectOptions? options,
  }) {
    final driver = PostgresDriver.connect(
      url,
      migrations: _$conduitDatabaseMigrations,
      options: options,
    );
    return _$ConduitDatabase._(driver);
  }

  final PostgresDriver _driver;

  @override
  Connection get connection => _driver;

  @override
  Future<Result<Unit, SqlxError>> migrate() => _driver.migrate();

  @override
  UnsafeSql get unsafe => PostgresUnsafeSql(_driver);

  Pool get pool => _driver;
}

const Map<String, String> _$conduitDatabaseMigrations = <String, String>{
  '20260926000001_create_users.up.sql': '-- Users.\n--\n-- Uniqueness lives in the database, not in a SELECT before an INSERT: two\n-- sign-ups racing for one username both pass a check-then-write, and only a\n-- unique index stops the second. The handlers turn the resulting SQLSTATE 23505\n-- into a 409 by constraint name, so the index names are part of the contract.\n--\n-- Timestamps default to now(), which is fixed for the whole statement, so a new\n-- row\'s created_at and updated_at are equal. clock_timestamp() is read once\n-- per column and can differ by a microsecond between the two.\nCREATE TABLE users (\n  id            BIGSERIAL PRIMARY KEY,\n  username      TEXT NOT NULL,\n  email         TEXT NOT NULL,\n  password_hash TEXT NOT NULL,\n  bio           TEXT,\n  image         TEXT,\n  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n\n-- Case-insensitive, so `Ada` cannot register next to `ada` and impersonate her.\nCREATE UNIQUE INDEX users_username_key ON users (lower(username));\nCREATE UNIQUE INDEX users_email_key ON users (lower(email));\n',
  '20260926000002_create_follows.up.sql': '-- Who follows whom.\nCREATE TABLE follows (\n  follower_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,\n  followee_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,\n  PRIMARY KEY (follower_id, followee_id),\n  CHECK (follower_id <> followee_id)\n);\n\n-- The feed asks "who does this user follow"; the primary key answers that.\n-- A profile page asks the reverse, which needs its own index.\nCREATE INDEX follows_followee ON follows (followee_id);\n',
  '20260926000003_create_articles.up.sql': '-- Articles.\n--\n-- Tags are a TEXT[] on the article rather than a join table: an article owns a\n-- short, ordered list, and PostgreSQL arrays keep the order the author gave.\n-- The GIN index serves `tag_list @> ARRAY[\$1]`, the "filter by tag" query.\nCREATE TABLE articles (\n  id          BIGSERIAL PRIMARY KEY,\n  slug        TEXT NOT NULL CONSTRAINT articles_slug_key UNIQUE,\n  title       TEXT NOT NULL,\n  description TEXT NOT NULL,\n  body        TEXT NOT NULL,\n  tag_list    TEXT[] NOT NULL DEFAULT \'{}\',\n  author_id   BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,\n  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n\nCREATE INDEX articles_recent ON articles (created_at DESC, id DESC);\nCREATE INDEX articles_author_recent ON articles (author_id, created_at DESC);\nCREATE INDEX articles_tag_list ON articles USING GIN (tag_list);\n',
  '20260926000004_create_favorites.up.sql': '-- Which users favorited which articles.\nCREATE TABLE favorites (\n  user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,\n  article_id BIGINT NOT NULL REFERENCES articles (id) ON DELETE CASCADE,\n  PRIMARY KEY (user_id, article_id)\n);\n\nCREATE INDEX favorites_article ON favorites (article_id);\n',
  '20260926000005_create_comments.up.sql': '-- Comments on articles.\nCREATE TABLE comments (\n  id         BIGSERIAL PRIMARY KEY,\n  article_id BIGINT NOT NULL REFERENCES articles (id) ON DELETE CASCADE,\n  author_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,\n  body       TEXT NOT NULL,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n\nCREATE INDEX comments_article ON comments (article_id, id DESC);\n',
};
