// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'rows.dart';

UserRow _$UserRowFromRow(Row row) {
  return UserRow(
    id: row.read<int>('id'),
    username: row.read<String>('username'),
    email: row.read<String>('email'),
    passwordHash: row.read<String>('password_hash'),
    bio: row.readNullable<String>('bio'),
    image: row.readNullable<String>('image'),
  );
}

/// Row deserializer for [UserRow].
final class $UserRowRowDeserializer implements RowDeserializer<UserRow> {
  const $UserRowRowDeserializer();

  @override
  UserRow deserialize(Row row) => _$UserRowFromRow(row);
}

/// Typed row query terminals for [UserRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $UserRowQuery on QueryAs<UserRow> {
  /// Fetches exactly one row.
  Future<Result<UserRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$UserRowFromRow);

  /// Fetches zero or one row.
  Future<Result<UserRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$UserRowFromRow);

  /// Fetches every row.
  Future<Result<List<UserRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$UserRowFromRow);
}

ProfileRow _$ProfileRowFromRow(Row row) {
  return ProfileRow(
    id: row.read<int>('id'),
    username: row.read<String>('username'),
    following: row.readBool('following'),
    bio: row.readNullable<String>('bio'),
    image: row.readNullable<String>('image'),
  );
}

/// Row deserializer for [ProfileRow].
final class $ProfileRowRowDeserializer implements RowDeserializer<ProfileRow> {
  const $ProfileRowRowDeserializer();

  @override
  ProfileRow deserialize(Row row) => _$ProfileRowFromRow(row);
}

/// Typed row query terminals for [ProfileRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ProfileRowQuery on QueryAs<ProfileRow> {
  /// Fetches exactly one row.
  Future<Result<ProfileRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ProfileRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ProfileRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ProfileRowFromRow);

  /// Fetches every row.
  Future<Result<List<ProfileRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ProfileRowFromRow);
}

ArticleRow _$ArticleRowFromRow(Row row) {
  return ArticleRow(
    id: row.read<int>('id'),
    slug: row.read<String>('slug'),
    title: row.read<String>('title'),
    description: row.read<String>('description'),
    tagList: TextArray().decode(row.read<List<Object?>>('tag_list')),
    createdAt: row.readDateTime('created_at'),
    updatedAt: row.readDateTime('updated_at'),
    favorited: row.readBool('favorited'),
    favoritesCount: row.read<int>('favorites_count'),
    authorId: row.read<int>('author_id'),
    authorUsername: row.read<String>('author_username'),
    authorFollowing: row.readBool('author_following'),
    body: row.readNullable<String>('body'),
    authorBio: row.readNullable<String>('author_bio'),
    authorImage: row.readNullable<String>('author_image'),
  );
}

/// Row deserializer for [ArticleRow].
final class $ArticleRowRowDeserializer implements RowDeserializer<ArticleRow> {
  const $ArticleRowRowDeserializer();

  @override
  ArticleRow deserialize(Row row) => _$ArticleRowFromRow(row);
}

/// Typed row query terminals for [ArticleRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ArticleRowQuery on QueryAs<ArticleRow> {
  /// Fetches exactly one row.
  Future<Result<ArticleRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ArticleRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ArticleRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ArticleRowFromRow);

  /// Fetches every row.
  Future<Result<List<ArticleRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ArticleRowFromRow);
}

ArticleKey _$ArticleKeyFromRow(Row row) {
  return ArticleKey(
    id: row.read<int>('id'),
    slug: row.read<String>('slug'),
    authorId: row.read<int>('author_id'),
    title: row.read<String>('title'),
    description: row.read<String>('description'),
    body: row.read<String>('body'),
    tagList: TextArray().decode(row.read<List<Object?>>('tag_list')),
  );
}

/// Row deserializer for [ArticleKey].
final class $ArticleKeyRowDeserializer implements RowDeserializer<ArticleKey> {
  const $ArticleKeyRowDeserializer();

  @override
  ArticleKey deserialize(Row row) => _$ArticleKeyFromRow(row);
}

/// Typed row query terminals for [ArticleKey].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ArticleKeyQuery on QueryAs<ArticleKey> {
  /// Fetches exactly one row.
  Future<Result<ArticleKey, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ArticleKeyFromRow);

  /// Fetches zero or one row.
  Future<Result<ArticleKey?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ArticleKeyFromRow);

  /// Fetches every row.
  Future<Result<List<ArticleKey>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ArticleKeyFromRow);
}

CommentRow _$CommentRowFromRow(Row row) {
  return CommentRow(
    id: row.read<int>('id'),
    body: row.read<String>('body'),
    createdAt: row.readDateTime('created_at'),
    updatedAt: row.readDateTime('updated_at'),
    authorId: row.read<int>('author_id'),
    authorUsername: row.read<String>('author_username'),
    authorFollowing: row.readBool('author_following'),
    authorBio: row.readNullable<String>('author_bio'),
    authorImage: row.readNullable<String>('author_image'),
  );
}

/// Row deserializer for [CommentRow].
final class $CommentRowRowDeserializer implements RowDeserializer<CommentRow> {
  const $CommentRowRowDeserializer();

  @override
  CommentRow deserialize(Row row) => _$CommentRowFromRow(row);
}

/// Typed row query terminals for [CommentRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $CommentRowQuery on QueryAs<CommentRow> {
  /// Fetches exactly one row.
  Future<Result<CommentRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$CommentRowFromRow);

  /// Fetches zero or one row.
  Future<Result<CommentRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$CommentRowFromRow);

  /// Fetches every row.
  Future<Result<List<CommentRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$CommentRowFromRow);
}

NewCommentRow _$NewCommentRowFromRow(Row row) {
  return NewCommentRow(
    id: row.read<int>('id'),
    body: row.read<String>('body'),
    createdAt: row.readDateTime('created_at'),
    updatedAt: row.readDateTime('updated_at'),
  );
}

/// Row deserializer for [NewCommentRow].
final class $NewCommentRowRowDeserializer implements RowDeserializer<NewCommentRow> {
  const $NewCommentRowRowDeserializer();

  @override
  NewCommentRow deserialize(Row row) => _$NewCommentRowFromRow(row);
}

/// Typed row query terminals for [NewCommentRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $NewCommentRowQuery on QueryAs<NewCommentRow> {
  /// Fetches exactly one row.
  Future<Result<NewCommentRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$NewCommentRowFromRow);

  /// Fetches zero or one row.
  Future<Result<NewCommentRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$NewCommentRowFromRow);

  /// Fetches every row.
  Future<Result<List<NewCommentRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$NewCommentRowFromRow);
}

CommentKey _$CommentKeyFromRow(Row row) {
  return CommentKey(
    id: row.read<int>('id'),
    articleId: row.read<int>('article_id'),
    authorId: row.read<int>('author_id'),
  );
}

/// Row deserializer for [CommentKey].
final class $CommentKeyRowDeserializer implements RowDeserializer<CommentKey> {
  const $CommentKeyRowDeserializer();

  @override
  CommentKey deserialize(Row row) => _$CommentKeyFromRow(row);
}

/// Typed row query terminals for [CommentKey].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $CommentKeyQuery on QueryAs<CommentKey> {
  /// Fetches exactly one row.
  Future<Result<CommentKey, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$CommentKeyFromRow);

  /// Fetches zero or one row.
  Future<Result<CommentKey?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$CommentKeyFromRow);

  /// Fetches every row.
  Future<Result<List<CommentKey>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$CommentKeyFromRow);
}

TagRow _$TagRowFromRow(Row row) {
  return TagRow(
    tag: row.read<String>('tag'),
    uses: row.read<int>('uses'),
  );
}

/// Row deserializer for [TagRow].
final class $TagRowRowDeserializer implements RowDeserializer<TagRow> {
  const $TagRowRowDeserializer();

  @override
  TagRow deserialize(Row row) => _$TagRowFromRow(row);
}

/// Typed row query terminals for [TagRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $TagRowQuery on QueryAs<TagRow> {
  /// Fetches exactly one row.
  Future<Result<TagRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$TagRowFromRow);

  /// Fetches zero or one row.
  Future<Result<TagRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$TagRowFromRow);

  /// Fetches every row.
  Future<Result<List<TagRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$TagRowFromRow);
}
