// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'users_repo.dart';

final class _$UsersRepo implements UsersRepo {
  const _$UsersRepo(this._db);

  final Executor _db;

  @override
  Future<Result<UserRow, SqlxError>> insert(String username, String email, String passwordHash) {
    return _db.fetchOne<UserRow>(
      r'''
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, bio, image
''',
      [username, email, passwordHash],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byId(int id) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT id, username, email, password_hash, bio, image FROM users
WHERE id = $1
''',
      [id],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byEmail(String email) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT id, username, email, password_hash, bio, image FROM users
WHERE lower(email) = lower($1)
''',
      [email],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow, SqlxError>> update(int id, String username, String email, String passwordHash, String? bio, String? image) {
    return _db.fetchOne<UserRow>(
      r'''
UPDATE users
SET username = $2, email = $3, password_hash = $4, bio = $5, image = $6
WHERE id = $1
RETURNING id, username, email, password_hash, bio, image
''',
      [id, username, email, passwordHash, bio, image],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<ProfileRow?, SqlxError>> profile(String username, int viewerId) {
    return _db.fetchOptional<ProfileRow>(
      r'''
SELECT u.id, u.username, u.bio, u.image,
       EXISTS (
         SELECT 1 FROM follows f
         WHERE f.follower_id = $2 AND f.followee_id = u.id
       ) AS following
FROM users u
WHERE u.username = $1
''',
      [username, viewerId],
      const $ProfileRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> follow(int followerId, int followeeId) {
    return _db.execute(
      r'''
INSERT INTO follows (follower_id, followee_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
''',
      [followerId, followeeId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> unfollow(int followerId, int followeeId) {
    return _db.execute(
      r'''
DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2
''',
      [followerId, followeeId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
