// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'article.dart';

const DeepCollectionEquality _articleTagListEquality = DeepCollectionEquality();
const DeepCollectionEquality _articlePreviewTagListEquality = DeepCollectionEquality();
const DeepCollectionEquality _articlesPageArticlesEquality = DeepCollectionEquality();
const DeepCollectionEquality _updateArticleTagListEquality = DeepCollectionEquality();

mixin _$Article implements Serializable {
  @override
  String toString() {
    final self = this as Article;
    return 'Article('
        'slug: ${self.slug}, '
        'title: ${self.title}, '
        'description: ${self.description}, '
        'body: ${self.body}, '
        'tagList: ${self.tagList}, '
        'createdAt: ${self.createdAt}, '
        'updatedAt: ${self.updatedAt}, '
        'favorited: ${self.favorited}, '
        'favoritesCount: ${self.favoritesCount}, '
        'author: ${self.author}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Article;
    return identical(this, other) ||
        other is Article &&
            runtimeType == other.runtimeType &&
            other.slug == self.slug &&
            other.title == self.title &&
            other.description == self.description &&
            other.body == self.body &&
            _articleTagListEquality.equals(other.tagList, self.tagList) &&
            other.createdAt == self.createdAt &&
            other.updatedAt == self.updatedAt &&
            other.favorited == self.favorited &&
            other.favoritesCount == self.favoritesCount &&
            other.author == self.author;
  }

  @override
  int get hashCode {
    final self = this as Article;
    return Object.hashAll([
      runtimeType,
      self.slug,
      self.title,
      self.description,
      self.body,
      _articleTagListEquality.hash(self.tagList),
      self.createdAt,
      self.updatedAt,
      self.favorited,
      self.favoritesCount,
      self.author,
    ]);
  }

  /// Creates a copy of this `Article` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = article.copyWith(slug: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$ArticleCopyWith<Article> get copyWith => _$ArticleCopyWithImpl<Article>(this as Article, (value) => value);

  Map<String, Object?> serialize() => _$ArticleSerialize(this as Article);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ArticlePreview implements Serializable {
  @override
  String toString() {
    final self = this as ArticlePreview;
    return 'ArticlePreview('
        'slug: ${self.slug}, '
        'title: ${self.title}, '
        'description: ${self.description}, '
        'tagList: ${self.tagList}, '
        'createdAt: ${self.createdAt}, '
        'updatedAt: ${self.updatedAt}, '
        'favorited: ${self.favorited}, '
        'favoritesCount: ${self.favoritesCount}, '
        'author: ${self.author}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ArticlePreview;
    return identical(this, other) ||
        other is ArticlePreview &&
            runtimeType == other.runtimeType &&
            other.slug == self.slug &&
            other.title == self.title &&
            other.description == self.description &&
            _articlePreviewTagListEquality.equals(other.tagList, self.tagList) &&
            other.createdAt == self.createdAt &&
            other.updatedAt == self.updatedAt &&
            other.favorited == self.favorited &&
            other.favoritesCount == self.favoritesCount &&
            other.author == self.author;
  }

  @override
  int get hashCode {
    final self = this as ArticlePreview;
    return Object.hashAll([
      runtimeType,
      self.slug,
      self.title,
      self.description,
      _articlePreviewTagListEquality.hash(self.tagList),
      self.createdAt,
      self.updatedAt,
      self.favorited,
      self.favoritesCount,
      self.author,
    ]);
  }

  /// Creates a copy of this `ArticlePreview` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = articlePreview.copyWith(slug: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$ArticlePreviewCopyWith<ArticlePreview> get copyWith => _$ArticlePreviewCopyWithImpl<ArticlePreview>(this as ArticlePreview, (value) => value);

  Map<String, Object?> serialize() =>
      _$ArticlePreviewSerialize(this as ArticlePreview);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ArticleEnvelope implements Serializable {
  @override
  String toString() {
    final self = this as ArticleEnvelope;
    return 'ArticleEnvelope('
        'article: ${self.article}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ArticleEnvelope;
    return identical(this, other) ||
        other is ArticleEnvelope &&
            runtimeType == other.runtimeType &&
            other.article == self.article;
  }

  @override
  int get hashCode {
    final self = this as ArticleEnvelope;
    return Object.hashAll([
      runtimeType,
      self.article,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$ArticleEnvelopeSerialize(this as ArticleEnvelope);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ArticlesPage implements Serializable {
  @override
  String toString() {
    final self = this as ArticlesPage;
    return 'ArticlesPage('
        'articles: ${self.articles}, '
        'articlesCount: ${self.articlesCount}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ArticlesPage;
    return identical(this, other) ||
        other is ArticlesPage &&
            runtimeType == other.runtimeType &&
            _articlesPageArticlesEquality.equals(other.articles, self.articles) &&
            other.articlesCount == self.articlesCount;
  }

  @override
  int get hashCode {
    final self = this as ArticlesPage;
    return Object.hashAll([
      runtimeType,
      _articlesPageArticlesEquality.hash(self.articles),
      self.articlesCount,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$ArticlesPageSerialize(this as ArticlesPage);

  Map<String, Object?> toJson() => serialize();
}

mixin _$NewArticle implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as NewArticle;
    return 'NewArticle('
        'title: ${self.title}, '
        'description: ${self.description}, '
        'body: ${self.body}, '
        'tagList: ${self.tagList}'
        ')';
  }

  /// Validates this `NewArticle`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as NewArticle;
    final errors = <ValidationError>[];
    _NewArticleValidation._validateTitle(self.title, errors);
    _NewArticleValidation._validateDescription(self.description, errors);
    _NewArticleValidation._validateBody(self.body, errors);
    _NewArticleValidation._validateTagList(self.tagList, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `NewArticle` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() => _$NewArticleSerialize(this as NewArticle);

  Map<String, Object?> toJson() => serialize();
}

mixin _$NewArticleRequest implements Serializable {
  Map<String, Object?> serialize() =>
      _$NewArticleRequestSerialize(this as NewArticleRequest);

  Map<String, Object?> toJson() => serialize();
}

mixin _$UpdateArticle implements Validatable {
  @override
  String toString() {
    final self = this as UpdateArticle;
    return 'UpdateArticle('
        'title: ${self.title}, '
        'description: ${self.description}, '
        'body: ${self.body}, '
        'tagList: ${self.tagList}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as UpdateArticle;
    return identical(this, other) ||
        other is UpdateArticle &&
            runtimeType == other.runtimeType &&
            other.title == self.title &&
            other.description == self.description &&
            other.body == self.body &&
            _updateArticleTagListEquality.equals(other.tagList, self.tagList);
  }

  @override
  int get hashCode {
    final self = this as UpdateArticle;
    return Object.hashAll([
      runtimeType,
      self.title,
      self.description,
      self.body,
      _updateArticleTagListEquality.hash(self.tagList),
    ]);
  }

  /// Validates this `UpdateArticle`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as UpdateArticle;
    final errors = <ValidationError>[];
    _UpdateArticleValidation._validateTitle(self.title, errors);
    _UpdateArticleValidation._validateDescription(self.description, errors);
    _UpdateArticleValidation._validateBody(self.body, errors);
    _UpdateArticleValidation._validateTagList(self.tagList, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `UpdateArticle` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }
}

mixin _$UpdateArticleRequest implements Serializable {
  Map<String, Object?> serialize() =>
      _$UpdateArticleRequestSerialize(this as UpdateArticleRequest);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ArticleCopyWith<$Res> {
  $Res call({
    String? slug,
    String? title,
    String? description,
    String? body,
    List<String>? tagList,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? favorited,
    int? favoritesCount,
    Profile? author,
  });
}

/// @nodoc
final class _$ArticleCopyWithImpl<$Res> implements _$ArticleCopyWith<$Res> {
  const _$ArticleCopyWithImpl(this._self, this._then);

  final Article _self;
  final $Res Function(Article) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? slug = null,
    Object? title = null,
    Object? description = null,
    Object? body = null,
    Object? tagList = null,
    Object? createdAt = null,
    Object? updatedAt = null,
    Object? favorited = null,
    Object? favoritesCount = null,
    Object? author = null,
  }) {
    return _then(
      Article(
        slug: slug == null ? _self.slug : slug as String,
        title: title == null ? _self.title : title as String,
        description: description == null ? _self.description : description as String,
        body: body == null ? _self.body : body as String,
        tagList: tagList == null ? _self.tagList : tagList as List<String>,
        createdAt: createdAt == null ? _self.createdAt : createdAt as DateTime,
        updatedAt: updatedAt == null ? _self.updatedAt : updatedAt as DateTime,
        favorited: favorited == null ? _self.favorited : favorited as bool,
        favoritesCount: favoritesCount == null ? _self.favoritesCount : favoritesCount as int,
        author: author == null ? _self.author : author as Profile,
      )
    );
  }
}
/// @nodoc
abstract class _$ArticlePreviewCopyWith<$Res> {
  $Res call({
    String? slug,
    String? title,
    String? description,
    List<String>? tagList,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? favorited,
    int? favoritesCount,
    Profile? author,
  });
}

/// @nodoc
final class _$ArticlePreviewCopyWithImpl<$Res> implements _$ArticlePreviewCopyWith<$Res> {
  const _$ArticlePreviewCopyWithImpl(this._self, this._then);

  final ArticlePreview _self;
  final $Res Function(ArticlePreview) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? slug = null,
    Object? title = null,
    Object? description = null,
    Object? tagList = null,
    Object? createdAt = null,
    Object? updatedAt = null,
    Object? favorited = null,
    Object? favoritesCount = null,
    Object? author = null,
  }) {
    return _then(
      ArticlePreview(
        slug: slug == null ? _self.slug : slug as String,
        title: title == null ? _self.title : title as String,
        description: description == null ? _self.description : description as String,
        tagList: tagList == null ? _self.tagList : tagList as List<String>,
        createdAt: createdAt == null ? _self.createdAt : createdAt as DateTime,
        updatedAt: updatedAt == null ? _self.updatedAt : updatedAt as DateTime,
        favorited: favorited == null ? _self.favorited : favorited as bool,
        favoritesCount: favoritesCount == null ? _self.favoritesCount : favoritesCount as int,
        author: author == null ? _self.author : author as Profile,
      )
    );
  }
}
extension _NewArticleValidation on NewArticle {
  static void _validateTitle(String title, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(title)) {
      errors.add(ValidationError(field: 'title', message: 'can\'t be blank'));
    }
    if (title.length > 200) {
      errors.add(ValidationError(field: 'title', message: 'is too long (maximum is 200 characters)'));
    }
  }

  static void _validateDescription(String description, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(description)) {
      errors.add(ValidationError(field: 'description', message: 'can\'t be blank'));
    }
    if (description.length > 500) {
      errors.add(ValidationError(field: 'description', message: 'is too long (maximum is 500 characters)'));
    }
  }

  static void _validateBody(String body, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(body)) {
      errors.add(ValidationError(field: 'body', message: 'can\'t be blank'));
    }
  }

  static void _validateTagList(List<String> tagList, List<ValidationError> errors) {
    if (tagList.length > 20) {
      errors.add(ValidationError(field: 'tagList', message: 'has too many tags (maximum is 20)'));
    }
  }

}
extension _UpdateArticleValidation on UpdateArticle {
  static void _validateTitle(String? title, List<ValidationError> errors) {
    if (title != null) {
      if (!RegExp('\\S').hasMatch(title)) {
        errors.add(ValidationError(field: 'title', message: 'can\'t be blank'));
      }
    }
    if (title != null) {
      if (title.length > 200) {
        errors.add(ValidationError(field: 'title', message: 'is too long (maximum is 200 characters)'));
      }
    }
  }

  static void _validateDescription(String? description, List<ValidationError> errors) {
    if (description != null) {
      if (!RegExp('\\S').hasMatch(description)) {
        errors.add(ValidationError(field: 'description', message: 'can\'t be blank'));
      }
    }
    if (description != null) {
      if (description.length > 500) {
        errors.add(ValidationError(field: 'description', message: 'is too long (maximum is 500 characters)'));
      }
    }
  }

  static void _validateBody(String? body, List<ValidationError> errors) {
    if (body != null) {
      if (!RegExp('\\S').hasMatch(body)) {
        errors.add(ValidationError(field: 'body', message: 'can\'t be blank'));
      }
    }
  }

  static void _validateTagList(List<String>? tagList, List<ValidationError> errors) {
    if (tagList != null) {
      if (tagList.length > 20) {
        errors.add(ValidationError(field: 'tagList', message: 'has too many tags (maximum is 20)'));
      }
    }
  }

}
final class $ArticleSerializer implements Serializer<Article, Map<String, Object?>> {
  const $ArticleSerializer();

  @override
  Map<String, Object?> serialize(Article value) => _$ArticleSerialize(value);
}
final class $ArticleDeserializer implements Deserializer<Article, Map<String, Object?>> {
  const $ArticleDeserializer();

  @override
  Article deserialize(Map<String, Object?> json) => _$ArticleDeserialize(json);
}
final class $ArticlePreviewSerializer implements Serializer<ArticlePreview, Map<String, Object?>> {
  const $ArticlePreviewSerializer();

  @override
  Map<String, Object?> serialize(ArticlePreview value) => _$ArticlePreviewSerialize(value);
}
final class $ArticlePreviewDeserializer implements Deserializer<ArticlePreview, Map<String, Object?>> {
  const $ArticlePreviewDeserializer();

  @override
  ArticlePreview deserialize(Map<String, Object?> json) => _$ArticlePreviewDeserialize(json);
}
final class $ArticleEnvelopeSerializer implements Serializer<ArticleEnvelope, Map<String, Object?>> {
  const $ArticleEnvelopeSerializer();

  @override
  Map<String, Object?> serialize(ArticleEnvelope value) => _$ArticleEnvelopeSerialize(value);
}
final class $ArticleEnvelopeDeserializer implements Deserializer<ArticleEnvelope, Map<String, Object?>> {
  const $ArticleEnvelopeDeserializer();

  @override
  ArticleEnvelope deserialize(Map<String, Object?> json) => _$ArticleEnvelopeDeserialize(json);
}
final class $ArticlesPageSerializer implements Serializer<ArticlesPage, Map<String, Object?>> {
  const $ArticlesPageSerializer();

  @override
  Map<String, Object?> serialize(ArticlesPage value) => _$ArticlesPageSerialize(value);
}
final class $ArticlesPageDeserializer implements Deserializer<ArticlesPage, Map<String, Object?>> {
  const $ArticlesPageDeserializer();

  @override
  ArticlesPage deserialize(Map<String, Object?> json) => _$ArticlesPageDeserialize(json);
}
final class $NewArticleSerializer implements Serializer<NewArticle, Map<String, Object?>> {
  const $NewArticleSerializer();

  @override
  Map<String, Object?> serialize(NewArticle value) => _$NewArticleSerialize(value);
}
final class $NewArticleDeserializer implements Deserializer<NewArticle, Map<String, Object?>> {
  const $NewArticleDeserializer();

  @override
  NewArticle deserialize(Map<String, Object?> json) => _$NewArticleDeserialize(json);
}
final class $NewArticleRequestSerializer implements Serializer<NewArticleRequest, Map<String, Object?>> {
  const $NewArticleRequestSerializer();

  @override
  Map<String, Object?> serialize(NewArticleRequest value) => _$NewArticleRequestSerialize(value);
}
final class $NewArticleRequestDeserializer implements Deserializer<NewArticleRequest, Map<String, Object?>> {
  const $NewArticleRequestDeserializer();

  @override
  NewArticleRequest deserialize(Map<String, Object?> json) => _$NewArticleRequestDeserialize(json);
}
final class $UpdateArticleDeserializer implements Deserializer<UpdateArticle, Map<String, Object?>> {
  const $UpdateArticleDeserializer();

  @override
  UpdateArticle deserialize(Map<String, Object?> json) => _$UpdateArticleDeserialize(json);
}
final class $UpdateArticleRequestSerializer implements Serializer<UpdateArticleRequest, Map<String, Object?>> {
  const $UpdateArticleRequestSerializer();

  @override
  Map<String, Object?> serialize(UpdateArticleRequest value) => _$UpdateArticleRequestSerialize(value);
}
final class $UpdateArticleRequestDeserializer implements Deserializer<UpdateArticleRequest, Map<String, Object?>> {
  const $UpdateArticleRequestDeserializer();

  @override
  UpdateArticleRequest deserialize(Map<String, Object?> json) => _$UpdateArticleRequestDeserialize(json);
}

Map<String, Object?> _$ArticleSerialize(Article instance) {
  return <String, Object?>{
    'slug': instance.slug,
    'title': instance.title,
    'description': instance.description,
    'body': instance.body,
    'tagList': instance.tagList
        .map((item) => item)
        .toList(),
    'createdAt': instance.createdAt.toIso8601String(),
    'updatedAt': instance.updatedAt.toIso8601String(),
    'favorited': instance.favorited,
    'favoritesCount': instance.favoritesCount,
    'author': instance.author.toJson(),
  };
}

Map<String, Object?> _$ArticleToJson(Article instance) =>
    _$ArticleSerialize(instance);

// factory Article.fromJson(Map<String, Object?> json) => _$ArticleFromJson(json);
Article _$ArticleDeserialize(Map<String, Object?> json) {
  final slugValue = JsonHelper.as<String>(json['slug'], 'slug', 'String');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = JsonHelper.as<String>(
    json['description'],
    'description',
    'String',
  );
  final bodyValue = JsonHelper.as<String>(json['body'], 'body', 'String');
  final tagListValue = JsonHelper.decodeList(json['tagList'], 'tagList',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));
  final createdAtValue = JsonHelper.asDateTime(json['createdAt'], 'createdAt');
  final updatedAtValue = JsonHelper.asDateTime(json['updatedAt'], 'updatedAt');
  final favoritedValue = JsonHelper.as<bool>(
    json['favorited'],
    'favorited',
    'bool',
  );
  final favoritesCountValue = JsonHelper.as<int>(
    json['favoritesCount'],
    'favoritesCount',
    'int',
  );
  final authorValue = Profile.fromJson(
    JsonHelper.asMap(json['author'], 'author'),
  );

  return Article(
    slug: slugValue,
    title: titleValue,
    description: descriptionValue,
    body: bodyValue,
    tagList: tagListValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    favorited: favoritedValue,
    favoritesCount: favoritesCountValue,
    author: authorValue,
  );
}

Article _$ArticleFromJson(Map<String, Object?> json) =>
    _$ArticleDeserialize(json);

Map<String, Object?> _$ArticlePreviewSerialize(ArticlePreview instance) {
  return <String, Object?>{
    'slug': instance.slug,
    'title': instance.title,
    'description': instance.description,
    'tagList': instance.tagList
        .map((item) => item)
        .toList(),
    'createdAt': instance.createdAt.toIso8601String(),
    'updatedAt': instance.updatedAt.toIso8601String(),
    'favorited': instance.favorited,
    'favoritesCount': instance.favoritesCount,
    'author': instance.author.toJson(),
  };
}

Map<String, Object?> _$ArticlePreviewToJson(ArticlePreview instance) =>
    _$ArticlePreviewSerialize(instance);

// factory ArticlePreview.fromJson(Map<String, Object?> json) => _$ArticlePreviewFromJson(json);
ArticlePreview _$ArticlePreviewDeserialize(Map<String, Object?> json) {
  final slugValue = JsonHelper.as<String>(json['slug'], 'slug', 'String');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = JsonHelper.as<String>(
    json['description'],
    'description',
    'String',
  );
  final tagListValue = JsonHelper.decodeList(json['tagList'], 'tagList',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));
  final createdAtValue = JsonHelper.asDateTime(json['createdAt'], 'createdAt');
  final updatedAtValue = JsonHelper.asDateTime(json['updatedAt'], 'updatedAt');
  final favoritedValue = JsonHelper.as<bool>(
    json['favorited'],
    'favorited',
    'bool',
  );
  final favoritesCountValue = JsonHelper.as<int>(
    json['favoritesCount'],
    'favoritesCount',
    'int',
  );
  final authorValue = Profile.fromJson(
    JsonHelper.asMap(json['author'], 'author'),
  );

  return ArticlePreview(
    slug: slugValue,
    title: titleValue,
    description: descriptionValue,
    tagList: tagListValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    favorited: favoritedValue,
    favoritesCount: favoritesCountValue,
    author: authorValue,
  );
}

ArticlePreview _$ArticlePreviewFromJson(Map<String, Object?> json) =>
    _$ArticlePreviewDeserialize(json);

Map<String, Object?> _$ArticleEnvelopeSerialize(ArticleEnvelope instance) {
  return <String, Object?>{
    'article': _$ArticleSerialize(instance.article),
  };
}

Map<String, Object?> _$ArticleEnvelopeToJson(ArticleEnvelope instance) =>
    _$ArticleEnvelopeSerialize(instance);

// factory ArticleEnvelope.fromJson(Map<String, Object?> json) => _$ArticleEnvelopeFromJson(json);
ArticleEnvelope _$ArticleEnvelopeDeserialize(Map<String, Object?> json) {
  final articleValue = _$ArticleDeserialize(
    JsonHelper.asMap(json['article'], 'article'),
  );

  return ArticleEnvelope(article: articleValue);
}

ArticleEnvelope _$ArticleEnvelopeFromJson(Map<String, Object?> json) =>
    _$ArticleEnvelopeDeserialize(json);

Map<String, Object?> _$ArticlesPageSerialize(ArticlesPage instance) {
  return <String, Object?>{
    'articles': instance.articles
        .map((item) => _$ArticlePreviewSerialize(item))
        .toList(),
    'articlesCount': instance.articlesCount,
  };
}

Map<String, Object?> _$ArticlesPageToJson(ArticlesPage instance) =>
    _$ArticlesPageSerialize(instance);

// factory ArticlesPage.fromJson(Map<String, Object?> json) => _$ArticlesPageFromJson(json);
ArticlesPage _$ArticlesPageDeserialize(Map<String, Object?> json) {
  final articlesValue = JsonHelper.decodeList(json['articles'], 'articles',
      (item, itemKey) => _$ArticlePreviewDeserialize(JsonHelper.asMap(item, itemKey)));
  final articlesCountValue = JsonHelper.as<int>(
    json['articlesCount'],
    'articlesCount',
    'int',
  );

  return ArticlesPage(
    articles: articlesValue,
    articlesCount: articlesCountValue,
  );
}

ArticlesPage _$ArticlesPageFromJson(Map<String, Object?> json) =>
    _$ArticlesPageDeserialize(json);

Map<String, Object?> _$NewArticleSerialize(NewArticle instance) {
  return <String, Object?>{
    'title': instance.title,
    'description': instance.description,
    'body': instance.body,
    'tagList': instance.tagList
        .map((item) => item)
        .toList(),
  };
}

Map<String, Object?> _$NewArticleToJson(NewArticle instance) =>
    _$NewArticleSerialize(instance);

// factory NewArticle.fromJson(Map<String, Object?> json) => _$NewArticleFromJson(json);
NewArticle _$NewArticleDeserialize(Map<String, Object?> json) {
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = JsonHelper.as<String>(
    json['description'],
    'description',
    'String',
  );
  final bodyValue = JsonHelper.as<String>(json['body'], 'body', 'String');
  final tagListValue = json.containsKey('tagList')
      ? JsonHelper.decodeList(json['tagList'], 'tagList',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'))
      : <String>[];

  return NewArticle(
    title: titleValue,
    description: descriptionValue,
    body: bodyValue,
    tagList: tagListValue,
  );
}

NewArticle _$NewArticleFromJson(Map<String, Object?> json) =>
    _$NewArticleDeserialize(json);

Map<String, Object?> _$NewArticleRequestSerialize(NewArticleRequest instance) {
  return <String, Object?>{
    'article': _$NewArticleSerialize(instance.article),
  };
}

Map<String, Object?> _$NewArticleRequestToJson(NewArticleRequest instance) =>
    _$NewArticleRequestSerialize(instance);

// factory NewArticleRequest.fromJson(Map<String, Object?> json) => _$NewArticleRequestFromJson(json);
NewArticleRequest _$NewArticleRequestDeserialize(Map<String, Object?> json) {
  final articleValue = _$NewArticleDeserialize(
    JsonHelper.asMap(json['article'], 'article'),
  );

  return NewArticleRequest(article: articleValue);
}

NewArticleRequest _$NewArticleRequestFromJson(Map<String, Object?> json) =>
    _$NewArticleRequestDeserialize(json);

// factory UpdateArticle.fromJson(Map<String, Object?> json) => _$UpdateArticleFromJson(json);
UpdateArticle _$UpdateArticleDeserialize(Map<String, Object?> json) {
  final titleValue = json['title'] == null
      ? null
      : JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = json['description'] == null
      ? null
      : JsonHelper.as<String>(json['description'], 'description', 'String');
  final bodyValue = json['body'] == null
      ? null
      : JsonHelper.as<String>(json['body'], 'body', 'String');
  final tagListValue = json['tagList'] == null
      ? null
      : JsonHelper.decodeList(json['tagList'], 'tagList',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));

  return UpdateArticle(
    title: titleValue,
    description: descriptionValue,
    body: bodyValue,
    tagList: tagListValue,
  );
}

UpdateArticle _$UpdateArticleFromJson(Map<String, Object?> json) =>
    _$UpdateArticleDeserialize(json);

Map<String, Object?> _$UpdateArticleRequestSerialize(UpdateArticleRequest instance) {
  return <String, Object?>{
    'article': instance.article.toJson(),
  };
}

Map<String, Object?> _$UpdateArticleRequestToJson(UpdateArticleRequest instance) =>
    _$UpdateArticleRequestSerialize(instance);

// factory UpdateArticleRequest.fromJson(Map<String, Object?> json) => _$UpdateArticleRequestFromJson(json);
UpdateArticleRequest _$UpdateArticleRequestDeserialize(Map<String, Object?> json) {
  final articleValue = _$UpdateArticleDeserialize(
    JsonHelper.asMap(json['article'], 'article'),
  );

  return UpdateArticleRequest(article: articleValue);
}

UpdateArticleRequest _$UpdateArticleRequestFromJson(Map<String, Object?> json) =>
    _$UpdateArticleRequestDeserialize(json);
