// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'comment.dart';

const DeepCollectionEquality _commentsListCommentsEquality = DeepCollectionEquality();

mixin _$Comment implements Serializable {
  @override
  String toString() {
    final self = this as Comment;
    return 'Comment('
        'id: ${self.id}, '
        'createdAt: ${self.createdAt}, '
        'updatedAt: ${self.updatedAt}, '
        'body: ${self.body}, '
        'author: ${self.author}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Comment;
    return identical(this, other) ||
        other is Comment &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.createdAt == self.createdAt &&
            other.updatedAt == self.updatedAt &&
            other.body == self.body &&
            other.author == self.author;
  }

  @override
  int get hashCode {
    final self = this as Comment;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.createdAt,
      self.updatedAt,
      self.body,
      self.author,
    ]);
  }

  Map<String, Object?> serialize() => _$CommentSerialize(this as Comment);

  Map<String, Object?> toJson() => serialize();
}

mixin _$CommentEnvelope implements Serializable {
  @override
  String toString() {
    final self = this as CommentEnvelope;
    return 'CommentEnvelope('
        'comment: ${self.comment}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CommentEnvelope;
    return identical(this, other) ||
        other is CommentEnvelope &&
            runtimeType == other.runtimeType &&
            other.comment == self.comment;
  }

  @override
  int get hashCode {
    final self = this as CommentEnvelope;
    return Object.hashAll([
      runtimeType,
      self.comment,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$CommentEnvelopeSerialize(this as CommentEnvelope);

  Map<String, Object?> toJson() => serialize();
}

mixin _$CommentsList implements Serializable {
  @override
  String toString() {
    final self = this as CommentsList;
    return 'CommentsList('
        'comments: ${self.comments}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CommentsList;
    return identical(this, other) ||
        other is CommentsList &&
            runtimeType == other.runtimeType &&
            _commentsListCommentsEquality.equals(other.comments, self.comments);
  }

  @override
  int get hashCode {
    final self = this as CommentsList;
    return Object.hashAll([
      runtimeType,
      _commentsListCommentsEquality.hash(self.comments),
    ]);
  }

  Map<String, Object?> serialize() =>
      _$CommentsListSerialize(this as CommentsList);

  Map<String, Object?> toJson() => serialize();
}

mixin _$NewComment implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as NewComment;
    return 'NewComment('
        'body: ${self.body}'
        ')';
  }

  /// Validates this `NewComment`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as NewComment;
    final errors = <ValidationError>[];
    _NewCommentValidation._validateBody(self.body, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `NewComment` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() => _$NewCommentSerialize(this as NewComment);

  Map<String, Object?> toJson() => serialize();
}

mixin _$NewCommentRequest implements Serializable {
  Map<String, Object?> serialize() =>
      _$NewCommentRequestSerialize(this as NewCommentRequest);

  Map<String, Object?> toJson() => serialize();
}

extension _NewCommentValidation on NewComment {
  static void _validateBody(String body, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(body)) {
      errors.add(ValidationError(field: 'body', message: 'can\'t be blank'));
    }
    if (body.length > 5000) {
      errors.add(ValidationError(field: 'body', message: 'is too long (maximum is 5000 characters)'));
    }
  }

}
final class $CommentSerializer implements Serializer<Comment, Map<String, Object?>> {
  const $CommentSerializer();

  @override
  Map<String, Object?> serialize(Comment value) => _$CommentSerialize(value);
}
final class $CommentDeserializer implements Deserializer<Comment, Map<String, Object?>> {
  const $CommentDeserializer();

  @override
  Comment deserialize(Map<String, Object?> json) => _$CommentDeserialize(json);
}
final class $CommentEnvelopeSerializer implements Serializer<CommentEnvelope, Map<String, Object?>> {
  const $CommentEnvelopeSerializer();

  @override
  Map<String, Object?> serialize(CommentEnvelope value) => _$CommentEnvelopeSerialize(value);
}
final class $CommentEnvelopeDeserializer implements Deserializer<CommentEnvelope, Map<String, Object?>> {
  const $CommentEnvelopeDeserializer();

  @override
  CommentEnvelope deserialize(Map<String, Object?> json) => _$CommentEnvelopeDeserialize(json);
}
final class $CommentsListSerializer implements Serializer<CommentsList, Map<String, Object?>> {
  const $CommentsListSerializer();

  @override
  Map<String, Object?> serialize(CommentsList value) => _$CommentsListSerialize(value);
}
final class $CommentsListDeserializer implements Deserializer<CommentsList, Map<String, Object?>> {
  const $CommentsListDeserializer();

  @override
  CommentsList deserialize(Map<String, Object?> json) => _$CommentsListDeserialize(json);
}
final class $NewCommentSerializer implements Serializer<NewComment, Map<String, Object?>> {
  const $NewCommentSerializer();

  @override
  Map<String, Object?> serialize(NewComment value) => _$NewCommentSerialize(value);
}
final class $NewCommentDeserializer implements Deserializer<NewComment, Map<String, Object?>> {
  const $NewCommentDeserializer();

  @override
  NewComment deserialize(Map<String, Object?> json) => _$NewCommentDeserialize(json);
}
final class $NewCommentRequestSerializer implements Serializer<NewCommentRequest, Map<String, Object?>> {
  const $NewCommentRequestSerializer();

  @override
  Map<String, Object?> serialize(NewCommentRequest value) => _$NewCommentRequestSerialize(value);
}
final class $NewCommentRequestDeserializer implements Deserializer<NewCommentRequest, Map<String, Object?>> {
  const $NewCommentRequestDeserializer();

  @override
  NewCommentRequest deserialize(Map<String, Object?> json) => _$NewCommentRequestDeserialize(json);
}

Map<String, Object?> _$CommentSerialize(Comment instance) {
  return <String, Object?>{
    'id': instance.id,
    'createdAt': instance.createdAt.toIso8601String(),
    'updatedAt': instance.updatedAt.toIso8601String(),
    'body': instance.body,
    'author': instance.author.toJson(),
  };
}

Map<String, Object?> _$CommentToJson(Comment instance) =>
    _$CommentSerialize(instance);

// factory Comment.fromJson(Map<String, Object?> json) => _$CommentFromJson(json);
Comment _$CommentDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final createdAtValue = JsonHelper.asDateTime(json['createdAt'], 'createdAt');
  final updatedAtValue = JsonHelper.asDateTime(json['updatedAt'], 'updatedAt');
  final bodyValue = JsonHelper.as<String>(json['body'], 'body', 'String');
  final authorValue = Profile.fromJson(
    JsonHelper.asMap(json['author'], 'author'),
  );

  return Comment(
    id: idValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    body: bodyValue,
    author: authorValue,
  );
}

Comment _$CommentFromJson(Map<String, Object?> json) =>
    _$CommentDeserialize(json);

Map<String, Object?> _$CommentEnvelopeSerialize(CommentEnvelope instance) {
  return <String, Object?>{
    'comment': _$CommentSerialize(instance.comment),
  };
}

Map<String, Object?> _$CommentEnvelopeToJson(CommentEnvelope instance) =>
    _$CommentEnvelopeSerialize(instance);

// factory CommentEnvelope.fromJson(Map<String, Object?> json) => _$CommentEnvelopeFromJson(json);
CommentEnvelope _$CommentEnvelopeDeserialize(Map<String, Object?> json) {
  final commentValue = _$CommentDeserialize(
    JsonHelper.asMap(json['comment'], 'comment'),
  );

  return CommentEnvelope(comment: commentValue);
}

CommentEnvelope _$CommentEnvelopeFromJson(Map<String, Object?> json) =>
    _$CommentEnvelopeDeserialize(json);

Map<String, Object?> _$CommentsListSerialize(CommentsList instance) {
  return <String, Object?>{
    'comments': instance.comments
        .map((item) => _$CommentSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$CommentsListToJson(CommentsList instance) =>
    _$CommentsListSerialize(instance);

// factory CommentsList.fromJson(Map<String, Object?> json) => _$CommentsListFromJson(json);
CommentsList _$CommentsListDeserialize(Map<String, Object?> json) {
  final commentsValue = JsonHelper.decodeList(json['comments'], 'comments',
      (item, itemKey) => _$CommentDeserialize(JsonHelper.asMap(item, itemKey)));

  return CommentsList(comments: commentsValue);
}

CommentsList _$CommentsListFromJson(Map<String, Object?> json) =>
    _$CommentsListDeserialize(json);

Map<String, Object?> _$NewCommentSerialize(NewComment instance) {
  return <String, Object?>{
    'body': instance.body,
  };
}

Map<String, Object?> _$NewCommentToJson(NewComment instance) =>
    _$NewCommentSerialize(instance);

// factory NewComment.fromJson(Map<String, Object?> json) => _$NewCommentFromJson(json);
NewComment _$NewCommentDeserialize(Map<String, Object?> json) {
  final bodyValue = JsonHelper.as<String>(json['body'], 'body', 'String');

  return NewComment(body: bodyValue);
}

NewComment _$NewCommentFromJson(Map<String, Object?> json) =>
    _$NewCommentDeserialize(json);

Map<String, Object?> _$NewCommentRequestSerialize(NewCommentRequest instance) {
  return <String, Object?>{
    'comment': _$NewCommentSerialize(instance.comment),
  };
}

Map<String, Object?> _$NewCommentRequestToJson(NewCommentRequest instance) =>
    _$NewCommentRequestSerialize(instance);

// factory NewCommentRequest.fromJson(Map<String, Object?> json) => _$NewCommentRequestFromJson(json);
NewCommentRequest _$NewCommentRequestDeserialize(Map<String, Object?> json) {
  final commentValue = _$NewCommentDeserialize(
    JsonHelper.asMap(json['comment'], 'comment'),
  );

  return NewCommentRequest(comment: commentValue);
}

NewCommentRequest _$NewCommentRequestFromJson(Map<String, Object?> json) =>
    _$NewCommentRequestDeserialize(json);
