// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'profile.dart';

final class _ProfileCopyWithUnset {
  const _ProfileCopyWithUnset();
}

const _profileCopyWithUnset = _ProfileCopyWithUnset();

mixin _$Profile implements Serializable {
  @override
  String toString() {
    final self = this as Profile;
    return 'Profile('
        'username: ${self.username}, '
        'bio: ${self.bio}, '
        'image: ${self.image}, '
        'following: ${self.following}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Profile;
    return identical(this, other) ||
        other is Profile &&
            runtimeType == other.runtimeType &&
            other.username == self.username &&
            other.bio == self.bio &&
            other.image == self.image &&
            other.following == self.following;
  }

  @override
  int get hashCode {
    final self = this as Profile;
    return Object.hashAll([
      runtimeType,
      self.username,
      self.bio,
      self.image,
      self.following,
    ]);
  }

  /// Creates a copy of this `Profile` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = profile.copyWith(username: 'John');
  /// final cleared = profile.copyWith(bio: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$ProfileCopyWith<Profile> get copyWith => _$ProfileCopyWithImpl<Profile>(this as Profile, (value) => value);

  Map<String, Object?> serialize() => _$ProfileSerialize(this as Profile);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ProfileEnvelope implements Serializable {
  @override
  String toString() {
    final self = this as ProfileEnvelope;
    return 'ProfileEnvelope('
        'profile: ${self.profile}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProfileEnvelope;
    return identical(this, other) ||
        other is ProfileEnvelope &&
            runtimeType == other.runtimeType &&
            other.profile == self.profile;
  }

  @override
  int get hashCode {
    final self = this as ProfileEnvelope;
    return Object.hashAll([
      runtimeType,
      self.profile,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$ProfileEnvelopeSerialize(this as ProfileEnvelope);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ProfileCopyWith<$Res> {
  $Res call({
    String? username,
    String? bio,
    String? image,
    bool? following,
  });
}

/// @nodoc
final class _$ProfileCopyWithImpl<$Res> implements _$ProfileCopyWith<$Res> {
  const _$ProfileCopyWithImpl(this._self, this._then);

  final Profile _self;
  final $Res Function(Profile) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? username = null,
    Object? bio = _profileCopyWithUnset,
    Object? image = _profileCopyWithUnset,
    Object? following = null,
  }) {
    return _then(
      Profile(
        username: username == null ? _self.username : username as String,
        following: following == null ? _self.following : following as bool,
        bio: identical(bio, _profileCopyWithUnset)
            ? _self.bio
            : bio as String?,
        image: identical(image, _profileCopyWithUnset)
            ? _self.image
            : image as String?,
      )
    );
  }
}
final class $ProfileSerializer implements Serializer<Profile, Map<String, Object?>> {
  const $ProfileSerializer();

  @override
  Map<String, Object?> serialize(Profile value) => _$ProfileSerialize(value);
}
final class $ProfileDeserializer implements Deserializer<Profile, Map<String, Object?>> {
  const $ProfileDeserializer();

  @override
  Profile deserialize(Map<String, Object?> json) => _$ProfileDeserialize(json);
}
final class $ProfileEnvelopeSerializer implements Serializer<ProfileEnvelope, Map<String, Object?>> {
  const $ProfileEnvelopeSerializer();

  @override
  Map<String, Object?> serialize(ProfileEnvelope value) => _$ProfileEnvelopeSerialize(value);
}
final class $ProfileEnvelopeDeserializer implements Deserializer<ProfileEnvelope, Map<String, Object?>> {
  const $ProfileEnvelopeDeserializer();

  @override
  ProfileEnvelope deserialize(Map<String, Object?> json) => _$ProfileEnvelopeDeserialize(json);
}

Map<String, Object?> _$ProfileSerialize(Profile instance) {
  return <String, Object?>{
    'username': instance.username,
    'bio': instance.bio,
    'image': instance.image,
    'following': instance.following,
  };
}

Map<String, Object?> _$ProfileToJson(Profile instance) =>
    _$ProfileSerialize(instance);

// factory Profile.fromJson(Map<String, Object?> json) => _$ProfileFromJson(json);
Profile _$ProfileDeserialize(Map<String, Object?> json) {
  final usernameValue = JsonHelper.as<String>(
    json['username'],
    'username',
    'String',
  );
  final bioValue = json['bio'] == null
      ? null
      : JsonHelper.as<String>(json['bio'], 'bio', 'String');
  final imageValue = json['image'] == null
      ? null
      : JsonHelper.as<String>(json['image'], 'image', 'String');
  final followingValue = JsonHelper.as<bool>(
    json['following'],
    'following',
    'bool',
  );

  return Profile(
    username: usernameValue,
    following: followingValue,
    bio: bioValue,
    image: imageValue,
  );
}

Profile _$ProfileFromJson(Map<String, Object?> json) =>
    _$ProfileDeserialize(json);

Map<String, Object?> _$ProfileEnvelopeSerialize(ProfileEnvelope instance) {
  return <String, Object?>{
    'profile': _$ProfileSerialize(instance.profile),
  };
}

Map<String, Object?> _$ProfileEnvelopeToJson(ProfileEnvelope instance) =>
    _$ProfileEnvelopeSerialize(instance);

// factory ProfileEnvelope.fromJson(Map<String, Object?> json) => _$ProfileEnvelopeFromJson(json);
ProfileEnvelope _$ProfileEnvelopeDeserialize(Map<String, Object?> json) {
  final profileValue = _$ProfileDeserialize(
    JsonHelper.asMap(json['profile'], 'profile'),
  );

  return ProfileEnvelope(profile: profileValue);
}

ProfileEnvelope _$ProfileEnvelopeFromJson(Map<String, Object?> json) =>
    _$ProfileEnvelopeDeserialize(json);
