// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'tags.dart';

const DeepCollectionEquality _tagsListTagsEquality = DeepCollectionEquality();
const DeepCollectionEquality _apiErrorsErrorsEquality = DeepCollectionEquality();

mixin _$TagsList implements Serializable {
  @override
  String toString() {
    final self = this as TagsList;
    return 'TagsList('
        'tags: ${self.tags}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as TagsList;
    return identical(this, other) ||
        other is TagsList &&
            runtimeType == other.runtimeType &&
            _tagsListTagsEquality.equals(other.tags, self.tags);
  }

  @override
  int get hashCode {
    final self = this as TagsList;
    return Object.hashAll([
      runtimeType,
      _tagsListTagsEquality.hash(self.tags),
    ]);
  }

  Map<String, Object?> serialize() => _$TagsListSerialize(this as TagsList);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ApiErrors implements Serializable {
  @override
  String toString() {
    final self = this as ApiErrors;
    return 'ApiErrors('
        'errors: ${self.errors}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ApiErrors;
    return identical(this, other) ||
        other is ApiErrors &&
            runtimeType == other.runtimeType &&
            _apiErrorsErrorsEquality.equals(other.errors, self.errors);
  }

  @override
  int get hashCode {
    final self = this as ApiErrors;
    return Object.hashAll([
      runtimeType,
      _apiErrorsErrorsEquality.hash(self.errors),
    ]);
  }

  Map<String, Object?> serialize() => _$ApiErrorsSerialize(this as ApiErrors);

  Map<String, Object?> toJson() => serialize();
}

final class $TagsListSerializer implements Serializer<TagsList, Map<String, Object?>> {
  const $TagsListSerializer();

  @override
  Map<String, Object?> serialize(TagsList value) => _$TagsListSerialize(value);
}
final class $TagsListDeserializer implements Deserializer<TagsList, Map<String, Object?>> {
  const $TagsListDeserializer();

  @override
  TagsList deserialize(Map<String, Object?> json) => _$TagsListDeserialize(json);
}
final class $ApiErrorsSerializer implements Serializer<ApiErrors, Map<String, Object?>> {
  const $ApiErrorsSerializer();

  @override
  Map<String, Object?> serialize(ApiErrors value) => _$ApiErrorsSerialize(value);
}
final class $ApiErrorsDeserializer implements Deserializer<ApiErrors, Map<String, Object?>> {
  const $ApiErrorsDeserializer();

  @override
  ApiErrors deserialize(Map<String, Object?> json) => _$ApiErrorsDeserialize(json);
}

Map<String, Object?> _$TagsListSerialize(TagsList instance) {
  return <String, Object?>{
    'tags': instance.tags
        .map((item) => item)
        .toList(),
  };
}

Map<String, Object?> _$TagsListToJson(TagsList instance) =>
    _$TagsListSerialize(instance);

// factory TagsList.fromJson(Map<String, Object?> json) => _$TagsListFromJson(json);
TagsList _$TagsListDeserialize(Map<String, Object?> json) {
  final tagsValue = JsonHelper.decodeList(json['tags'], 'tags',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));

  return TagsList(tags: tagsValue);
}

TagsList _$TagsListFromJson(Map<String, Object?> json) =>
    _$TagsListDeserialize(json);

Map<String, Object?> _$ApiErrorsSerialize(ApiErrors instance) {
  return <String, Object?>{
    'errors': instance.errors
        .map(
          (key, value) => MapEntry(
            key,
            value
                .map((item) => item)
                .toList(),
          ),
        ),
  };
}

Map<String, Object?> _$ApiErrorsToJson(ApiErrors instance) =>
    _$ApiErrorsSerialize(instance);

// factory ApiErrors.fromJson(Map<String, Object?> json) => _$ApiErrorsFromJson(json);
ApiErrors _$ApiErrorsDeserialize(Map<String, Object?> json) {
  final errorsValue = JsonHelper.decodeMap(json['errors'], 'errors',
      (value, valueKey) =>
          JsonHelper.decodeList(value, valueKey,
              (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String')));

  return ApiErrors(errors: errorsValue);
}

ApiErrors _$ApiErrorsFromJson(Map<String, Object?> json) =>
    _$ApiErrorsDeserialize(json);
