// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'user.dart';

final class _UserCopyWithUnset {
  const _UserCopyWithUnset();
}

const _userCopyWithUnset = _UserCopyWithUnset();

mixin _$User implements Serializable {
  @override
  String toString() {
    final self = this as User;
    return 'User('
        'email: ${self.email}, '
        'token: ${self.token}, '
        'username: ${self.username}, '
        'bio: ${self.bio}, '
        'image: ${self.image}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as User;
    return identical(this, other) ||
        other is User &&
            runtimeType == other.runtimeType &&
            other.email == self.email &&
            other.token == self.token &&
            other.username == self.username &&
            other.bio == self.bio &&
            other.image == self.image;
  }

  @override
  int get hashCode {
    final self = this as User;
    return Object.hashAll([
      runtimeType,
      self.email,
      self.token,
      self.username,
      self.bio,
      self.image,
    ]);
  }

  /// Creates a copy of this `User` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = user.copyWith(email: 'John');
  /// final cleared = user.copyWith(bio: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$UserCopyWith<User> get copyWith => _$UserCopyWithImpl<User>(this as User, (value) => value);

  Map<String, Object?> serialize() => _$UserSerialize(this as User);

  Map<String, Object?> toJson() => serialize();
}

mixin _$UserEnvelope implements Serializable {
  @override
  String toString() {
    final self = this as UserEnvelope;
    return 'UserEnvelope('
        'user: ${self.user}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as UserEnvelope;
    return identical(this, other) ||
        other is UserEnvelope &&
            runtimeType == other.runtimeType &&
            other.user == self.user;
  }

  @override
  int get hashCode {
    final self = this as UserEnvelope;
    return Object.hashAll([
      runtimeType,
      self.user,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$UserEnvelopeSerialize(this as UserEnvelope);

  Map<String, Object?> toJson() => serialize();
}

mixin _$LoginUser implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as LoginUser;
    return 'LoginUser('
        'email: ${self.email}, '
        'password: ${self.password}'
        ')';
  }

  /// Validates this `LoginUser`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as LoginUser;
    final errors = <ValidationError>[];
    _LoginUserValidation._validateEmail(self.email, errors);
    _LoginUserValidation._validatePassword(self.password, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `LoginUser` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() => _$LoginUserSerialize(this as LoginUser);

  Map<String, Object?> toJson() => serialize();
}

mixin _$LoginRequest implements Serializable {
  Map<String, Object?> serialize() =>
      _$LoginRequestSerialize(this as LoginRequest);

  Map<String, Object?> toJson() => serialize();
}

mixin _$NewUser implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as NewUser;
    return 'NewUser('
        'username: ${self.username}, '
        'email: ${self.email}, '
        'password: ${self.password}'
        ')';
  }

  /// Validates this `NewUser`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as NewUser;
    final errors = <ValidationError>[];
    _NewUserValidation._validateUsername(self.username, errors);
    _NewUserValidation._validateEmail(self.email, errors);
    _NewUserValidation._validatePassword(self.password, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `NewUser` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() => _$NewUserSerialize(this as NewUser);

  Map<String, Object?> toJson() => serialize();
}

mixin _$RegisterRequest implements Serializable {
  Map<String, Object?> serialize() =>
      _$RegisterRequestSerialize(this as RegisterRequest);

  Map<String, Object?> toJson() => serialize();
}

mixin _$UpdateUser implements Validatable {
  @override
  String toString() {
    final self = this as UpdateUser;
    return 'UpdateUser('
        'email: ${self.email}, '
        'username: ${self.username}, '
        'password: ${self.password}, '
        'bio: ${self.bio}, '
        'image: ${self.image}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as UpdateUser;
    return identical(this, other) ||
        other is UpdateUser &&
            runtimeType == other.runtimeType &&
            other.email == self.email &&
            other.username == self.username &&
            other.password == self.password &&
            other.bio == self.bio &&
            other.image == self.image;
  }

  @override
  int get hashCode {
    final self = this as UpdateUser;
    return Object.hashAll([
      runtimeType,
      self.email,
      self.username,
      self.password,
      self.bio,
      self.image,
    ]);
  }

  /// Validates this `UpdateUser`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as UpdateUser;
    final errors = <ValidationError>[];
    _UpdateUserValidation._validateEmail(self.email, errors);
    _UpdateUserValidation._validateUsername(self.username, errors);
    _UpdateUserValidation._validatePassword(self.password, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `UpdateUser` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }
}

mixin _$UpdateUserRequest implements Serializable {
  Map<String, Object?> serialize() =>
      _$UpdateUserRequestSerialize(this as UpdateUserRequest);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$UserCopyWith<$Res> {
  $Res call({
    String? email,
    String? token,
    String? username,
    String? bio,
    String? image,
  });
}

/// @nodoc
final class _$UserCopyWithImpl<$Res> implements _$UserCopyWith<$Res> {
  const _$UserCopyWithImpl(this._self, this._then);

  final User _self;
  final $Res Function(User) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? email = null,
    Object? token = null,
    Object? username = null,
    Object? bio = _userCopyWithUnset,
    Object? image = _userCopyWithUnset,
  }) {
    return _then(
      User(
        email: email == null ? _self.email : email as String,
        token: token == null ? _self.token : token as String,
        username: username == null ? _self.username : username as String,
        bio: identical(bio, _userCopyWithUnset)
            ? _self.bio
            : bio as String?,
        image: identical(image, _userCopyWithUnset)
            ? _self.image
            : image as String?,
      )
    );
  }
}
extension _LoginUserValidation on LoginUser {
  static void _validateEmail(String email, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(email)) {
      errors.add(ValidationError(field: 'email', message: 'can\'t be blank'));
    }
  }

  static void _validatePassword(String password, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(password)) {
      errors.add(ValidationError(field: 'password', message: 'can\'t be blank'));
    }
  }

}
extension _NewUserValidation on NewUser {
  static void _validateUsername(String username, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(username)) {
      errors.add(ValidationError(field: 'username', message: 'can\'t be blank'));
    }
    if (username.length > 64) {
      errors.add(ValidationError(field: 'username', message: 'is too long (maximum is 64 characters)'));
    }
  }

  static void _validateEmail(String email, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(email)) {
      errors.add(ValidationError(field: 'email', message: 'can\'t be blank'));
    }
    if (!ValidationHelper.isEmail(email)) {
      errors.add(ValidationError(field: 'email', message: 'is invalid'));
    }
  }

  static void _validatePassword(String password, List<ValidationError> errors) {
    if (!RegExp('\\S').hasMatch(password)) {
      errors.add(ValidationError(field: 'password', message: 'can\'t be blank'));
    }
    if (password.length < 8) {
      errors.add(ValidationError(field: 'password', message: 'must be 8 to 256 characters'));
    }
    if (password.length > 256) {
      errors.add(ValidationError(field: 'password', message: 'must be 8 to 256 characters'));
    }
  }

}
extension _UpdateUserValidation on UpdateUser {
  static void _validateEmail(String? email, List<ValidationError> errors) {
    if (email != null) {
      if (!RegExp('\\S').hasMatch(email)) {
        errors.add(ValidationError(field: 'email', message: 'can\'t be blank'));
      }
    }
    if (email != null) {
      if (!ValidationHelper.isEmail(email)) {
        errors.add(ValidationError(field: 'email', message: 'is invalid'));
      }
    }
  }

  static void _validateUsername(String? username, List<ValidationError> errors) {
    if (username != null) {
      if (!RegExp('\\S').hasMatch(username)) {
        errors.add(ValidationError(field: 'username', message: 'can\'t be blank'));
      }
    }
    if (username != null) {
      if (username.length > 64) {
        errors.add(ValidationError(field: 'username', message: 'is too long (maximum is 64 characters)'));
      }
    }
  }

  static void _validatePassword(String? password, List<ValidationError> errors) {
    if (password != null) {
      if (password.length < 8) {
        errors.add(ValidationError(field: 'password', message: 'must be 8 to 256 characters'));
      }
      if (password.length > 256) {
        errors.add(ValidationError(field: 'password', message: 'must be 8 to 256 characters'));
      }
    }
  }

}
final class $UserSerializer implements Serializer<User, Map<String, Object?>> {
  const $UserSerializer();

  @override
  Map<String, Object?> serialize(User value) => _$UserSerialize(value);
}
final class $UserDeserializer implements Deserializer<User, Map<String, Object?>> {
  const $UserDeserializer();

  @override
  User deserialize(Map<String, Object?> json) => _$UserDeserialize(json);
}
final class $UserEnvelopeSerializer implements Serializer<UserEnvelope, Map<String, Object?>> {
  const $UserEnvelopeSerializer();

  @override
  Map<String, Object?> serialize(UserEnvelope value) => _$UserEnvelopeSerialize(value);
}
final class $UserEnvelopeDeserializer implements Deserializer<UserEnvelope, Map<String, Object?>> {
  const $UserEnvelopeDeserializer();

  @override
  UserEnvelope deserialize(Map<String, Object?> json) => _$UserEnvelopeDeserialize(json);
}
final class $LoginUserSerializer implements Serializer<LoginUser, Map<String, Object?>> {
  const $LoginUserSerializer();

  @override
  Map<String, Object?> serialize(LoginUser value) => _$LoginUserSerialize(value);
}
final class $LoginUserDeserializer implements Deserializer<LoginUser, Map<String, Object?>> {
  const $LoginUserDeserializer();

  @override
  LoginUser deserialize(Map<String, Object?> json) => _$LoginUserDeserialize(json);
}
final class $LoginRequestSerializer implements Serializer<LoginRequest, Map<String, Object?>> {
  const $LoginRequestSerializer();

  @override
  Map<String, Object?> serialize(LoginRequest value) => _$LoginRequestSerialize(value);
}
final class $LoginRequestDeserializer implements Deserializer<LoginRequest, Map<String, Object?>> {
  const $LoginRequestDeserializer();

  @override
  LoginRequest deserialize(Map<String, Object?> json) => _$LoginRequestDeserialize(json);
}
final class $NewUserSerializer implements Serializer<NewUser, Map<String, Object?>> {
  const $NewUserSerializer();

  @override
  Map<String, Object?> serialize(NewUser value) => _$NewUserSerialize(value);
}
final class $NewUserDeserializer implements Deserializer<NewUser, Map<String, Object?>> {
  const $NewUserDeserializer();

  @override
  NewUser deserialize(Map<String, Object?> json) => _$NewUserDeserialize(json);
}
final class $RegisterRequestSerializer implements Serializer<RegisterRequest, Map<String, Object?>> {
  const $RegisterRequestSerializer();

  @override
  Map<String, Object?> serialize(RegisterRequest value) => _$RegisterRequestSerialize(value);
}
final class $RegisterRequestDeserializer implements Deserializer<RegisterRequest, Map<String, Object?>> {
  const $RegisterRequestDeserializer();

  @override
  RegisterRequest deserialize(Map<String, Object?> json) => _$RegisterRequestDeserialize(json);
}
final class $UpdateUserDeserializer implements Deserializer<UpdateUser, Map<String, Object?>> {
  const $UpdateUserDeserializer();

  @override
  UpdateUser deserialize(Map<String, Object?> json) => _$UpdateUserDeserialize(json);
}
final class $UpdateUserRequestSerializer implements Serializer<UpdateUserRequest, Map<String, Object?>> {
  const $UpdateUserRequestSerializer();

  @override
  Map<String, Object?> serialize(UpdateUserRequest value) => _$UpdateUserRequestSerialize(value);
}
final class $UpdateUserRequestDeserializer implements Deserializer<UpdateUserRequest, Map<String, Object?>> {
  const $UpdateUserRequestDeserializer();

  @override
  UpdateUserRequest deserialize(Map<String, Object?> json) => _$UpdateUserRequestDeserialize(json);
}

Map<String, Object?> _$UserSerialize(User instance) {
  return <String, Object?>{
    'email': instance.email,
    'token': instance.token,
    'username': instance.username,
    'bio': instance.bio,
    'image': instance.image,
  };
}

Map<String, Object?> _$UserToJson(User instance) =>
    _$UserSerialize(instance);

// factory User.fromJson(Map<String, Object?> json) => _$UserFromJson(json);
User _$UserDeserialize(Map<String, Object?> json) {
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');
  final tokenValue = JsonHelper.as<String>(json['token'], 'token', 'String');
  final usernameValue = JsonHelper.as<String>(
    json['username'],
    'username',
    'String',
  );
  final bioValue = json['bio'] == null
      ? null
      : JsonHelper.as<String>(json['bio'], 'bio', 'String');
  final imageValue = json['image'] == null
      ? null
      : JsonHelper.as<String>(json['image'], 'image', 'String');

  return User(
    email: emailValue,
    token: tokenValue,
    username: usernameValue,
    bio: bioValue,
    image: imageValue,
  );
}

User _$UserFromJson(Map<String, Object?> json) =>
    _$UserDeserialize(json);

Map<String, Object?> _$UserEnvelopeSerialize(UserEnvelope instance) {
  return <String, Object?>{
    'user': _$UserSerialize(instance.user),
  };
}

Map<String, Object?> _$UserEnvelopeToJson(UserEnvelope instance) =>
    _$UserEnvelopeSerialize(instance);

// factory UserEnvelope.fromJson(Map<String, Object?> json) => _$UserEnvelopeFromJson(json);
UserEnvelope _$UserEnvelopeDeserialize(Map<String, Object?> json) {
  final userValue = _$UserDeserialize(JsonHelper.asMap(json['user'], 'user'));

  return UserEnvelope(user: userValue);
}

UserEnvelope _$UserEnvelopeFromJson(Map<String, Object?> json) =>
    _$UserEnvelopeDeserialize(json);

Map<String, Object?> _$LoginUserSerialize(LoginUser instance) {
  return <String, Object?>{
    'email': instance.email,
    'password': instance.password,
  };
}

Map<String, Object?> _$LoginUserToJson(LoginUser instance) =>
    _$LoginUserSerialize(instance);

// factory LoginUser.fromJson(Map<String, Object?> json) => _$LoginUserFromJson(json);
LoginUser _$LoginUserDeserialize(Map<String, Object?> json) {
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');
  final passwordValue = JsonHelper.as<String>(
    json['password'],
    'password',
    'String',
  );

  return LoginUser(email: emailValue, password: passwordValue);
}

LoginUser _$LoginUserFromJson(Map<String, Object?> json) =>
    _$LoginUserDeserialize(json);

Map<String, Object?> _$LoginRequestSerialize(LoginRequest instance) {
  return <String, Object?>{
    'user': _$LoginUserSerialize(instance.user),
  };
}

Map<String, Object?> _$LoginRequestToJson(LoginRequest instance) =>
    _$LoginRequestSerialize(instance);

// factory LoginRequest.fromJson(Map<String, Object?> json) => _$LoginRequestFromJson(json);
LoginRequest _$LoginRequestDeserialize(Map<String, Object?> json) {
  final userValue = _$LoginUserDeserialize(
    JsonHelper.asMap(json['user'], 'user'),
  );

  return LoginRequest(user: userValue);
}

LoginRequest _$LoginRequestFromJson(Map<String, Object?> json) =>
    _$LoginRequestDeserialize(json);

Map<String, Object?> _$NewUserSerialize(NewUser instance) {
  return <String, Object?>{
    'username': instance.username,
    'email': instance.email,
    'password': instance.password,
  };
}

Map<String, Object?> _$NewUserToJson(NewUser instance) =>
    _$NewUserSerialize(instance);

// factory NewUser.fromJson(Map<String, Object?> json) => _$NewUserFromJson(json);
NewUser _$NewUserDeserialize(Map<String, Object?> json) {
  final usernameValue = JsonHelper.as<String>(
    json['username'],
    'username',
    'String',
  );
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');
  final passwordValue = JsonHelper.as<String>(
    json['password'],
    'password',
    'String',
  );

  return NewUser(
    username: usernameValue,
    email: emailValue,
    password: passwordValue,
  );
}

NewUser _$NewUserFromJson(Map<String, Object?> json) =>
    _$NewUserDeserialize(json);

Map<String, Object?> _$RegisterRequestSerialize(RegisterRequest instance) {
  return <String, Object?>{
    'user': _$NewUserSerialize(instance.user),
  };
}

Map<String, Object?> _$RegisterRequestToJson(RegisterRequest instance) =>
    _$RegisterRequestSerialize(instance);

// factory RegisterRequest.fromJson(Map<String, Object?> json) => _$RegisterRequestFromJson(json);
RegisterRequest _$RegisterRequestDeserialize(Map<String, Object?> json) {
  final userValue = _$NewUserDeserialize(
    JsonHelper.asMap(json['user'], 'user'),
  );

  return RegisterRequest(user: userValue);
}

RegisterRequest _$RegisterRequestFromJson(Map<String, Object?> json) =>
    _$RegisterRequestDeserialize(json);

// factory UpdateUser.fromJson(Map<String, Object?> json) => _$UpdateUserFromJson(json);
UpdateUser _$UpdateUserDeserialize(Map<String, Object?> json) {
  final emailValue = json['email'] == null
      ? null
      : JsonHelper.as<String>(json['email'], 'email', 'String');
  final usernameValue = json['username'] == null
      ? null
      : JsonHelper.as<String>(json['username'], 'username', 'String');
  final passwordValue = json['password'] == null
      ? null
      : JsonHelper.as<String>(json['password'], 'password', 'String');
  final bioValue = json['bio'] == null
      ? null
      : JsonHelper.as<String>(json['bio'], 'bio', 'String');
  final imageValue = json['image'] == null
      ? null
      : JsonHelper.as<String>(json['image'], 'image', 'String');

  return UpdateUser(
    email: emailValue,
    username: usernameValue,
    password: passwordValue,
    bio: bioValue,
    image: imageValue,
  );
}

UpdateUser _$UpdateUserFromJson(Map<String, Object?> json) =>
    _$UpdateUserDeserialize(json);

Map<String, Object?> _$UpdateUserRequestSerialize(UpdateUserRequest instance) {
  return <String, Object?>{
    'user': instance.user.toJson(),
  };
}

Map<String, Object?> _$UpdateUserRequestToJson(UpdateUserRequest instance) =>
    _$UpdateUserRequestSerialize(instance);

// factory UpdateUserRequest.fromJson(Map<String, Object?> json) => _$UpdateUserRequestFromJson(json);
UpdateUserRequest _$UpdateUserRequestDeserialize(Map<String, Object?> json) {
  final userValue = _$UpdateUserDeserialize(
    JsonHelper.asMap(json['user'], 'user'),
  );

  return UpdateUserRequest(user: userValue);
}

UpdateUserRequest _$UpdateUserRequestFromJson(Map<String, Object?> json) =>
    _$UpdateUserRequestDeserialize(json);
